FROM gradle:7-jdk11-alpine AS build
RUN mkdir -p /app
COPY . /app
WORKDIR /app
RUN gradle bootJar

FROM adoptopenjdk/openjdk11:alpine-slim
COPY --from=build /app/build/libs/currency-bot-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]