apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app-name: {{ .Values.bot_app.name }}
  name: {{ .Values.bot_app.name }}
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app-name: {{ .Values.bot_app.name }}
status:
  loadBalancer: {}
