apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app-name: zookeeper1
  name: zookeeper1
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    app-name: zookeeper1
status:
  loadBalancer: {}
